### ISSUE TITLE
Implement tsp, linear and other paths.

### ISSUE THREAD

**Issue by arivero** [RocketMap/RocketMap#1560]
They are three scheduling paths:

- Full hexagon
- Hexagon except empty areas
- spawn teleporting (broken now)

To patrol across rivers, linear paths are an interesting alternative to hexagons.

Also, while the full hexagon is a solution to the traveling salesman problem, the -skip options are not. If points are removed from the hexagon, the best solution minimising jumps should be searched, in fact tsp is easier to compute for points in N paralell lines ("N-line Traveling Salesman Problem").

Other paths could be also interesting, eg to patrol for 200 meters sightings.

**Comment by arivero** [comment]
Related open issues: #1506 #1178

**Comment by baskettcase** [comment]
On this subject is there a way currently to feed the map a set of coordinates and it will scan at those coordinates? So for example a csv file, with 20 coordinates, will it scan those at this point? If not, then I would like to put this under your "other paths" functionality.

**Comment by baskettcase** [comment]
I didn't know I could do that. I'll see if I can figure out where in the docs it tells me how to do that. Thanks!

**Comment by birdstream** [comment]
I made a bash script that fed the map with new coordinates from a .csv file every hour to collect spawnpoints with hex-scanning (back when spawnpoint scan wasnt broken). It could be used for something like this :)

Naturally, this is on linux

`#!/bin/bash`

`while :`
` do`
`   while IFS=', ' read lat lon`
`     do`
`        curl "http://localhost:5000/next_loc?lat=${lat}&lon=${lon}" -X POST`
`        sleep 10`
`     done < your_coords_file.csv`
`done`

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
