### ISSUE TITLE
ERROR Map parse failed at xx abandoning location, map_dict['responses']['GET_MAP_OBJECTS']['map_cells']

### ISSUE THREAD

**Issue by dajoker17** [RocketMap/RocketMap#1926]
Multiple reports on discord of people receiving this error:
2017-03-11 19:42:27,730 [  search-worker-38][        search][   ERROR] Map parse failed at -xyz, abandoning location. dummyaccount may be banned.. Exception message: KeyError('GET_MAP_OBJECTS',)
Traceback (most recent call last):
  File "P:\pokemongo-map\pogom\search.py", line 991, in search_worker_thread
    dbq, whq, api, scan_date)
  File "P:\pokemongo-map\pogom\models.py", line 1704, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'GET_MAP_OBJECTS'

## Expected Behavior

When logging in on the phone the account is presented with "we have detected activity on you account......" and a button to press "got it"

Account isnt banned, and after a while will happily return to work.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by jangrewe** [comment]
http://rocketmap.readthedocs.io/en/develop/extras/faq.html?highlight=map_cells

#RTFM

**Comment by dajoker17** [comment]
manuals wrong or out of date, and clearly doesn't mention if you have a (new) warning on an account it will give the map cell error.

**Comment by jangrewe** [comment]
Sure, that applies generally to each and every manual of something that is in constant development. But this particular part is still correct.

**Comment by dajoker17** [comment]
sure whatever, not worth arguing with you about it. 
perhaps if you re-read the issue you might see the accounts are NOT banned, and return to work fine.

**Comment by jangrewe** [comment]
Just FYI, but there's not only hard, permanent bans, but also soft-bans that last a couple of minutes and up.

**Comment by jeremydevos** [comment]
I have the same issue.

Account its OK on PokemonGo APP, tut OK
On RockerMap this error : 
```
Unable to check captcha: 'CHECK_CHALLENGE'
Map parse failed at 50.639986,3.042009, abandoning location. **** may be banned.. Exception message: KeyError('GET_MAP_OBJECTS',)
Traceback (most recent call last):
  File "/root/RocketMap/pogom/search.py", line 991, in search_worker_thread
    dbq, whq, api, scan_date)
  File "/root/RocketMap/pogom/models.py", line 1704, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'GET_MAP_OBJECTS'
```

The server its OK, not banned, tested with : 
if curl https://pgorelease.nianticlabs.com/plfe/rpc -I | grep 403; then IP=$(curl checkip.amazonaws.com/);echo -n ", $IP" >> file ; else echo Not Banned; fi

**Comment by M3G4THEKING** [comment]
This error "Unable to check captcha: 'CHECK_CHALLENGE'
Map parse failed at 50.639986,3.042009, abandoning location. **** may be banned.. Exception message: KeyError('GET_MAP_OBJECTS',)
Traceback (most recent call last):
  File "/root/RocketMap/pogom/search.py", line 991, in search_worker_thread
    dbq, whq, api, scan_date)
  File "/root/RocketMap/pogom/models.py", line 1704, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'GET_MAP_OBJECTS'"   Is about the new api,they are working on this. If you use the old api 0.57.3 same account can scan without problems but gonna be flagged/banned.

**Comment by sirlindqvist** [comment]
I have this too randomly on some accounts and I have seen a lot of people asking about this. Started with 0.57.4, never had this error before. When accounts get this they just continue to scan (they don't get on hold).

**Comment by M3G4THEKING** [comment]
@sirlindqvist i have made several tests, new server new ips new installs new hashkey new accts -tut all lv3+ after 5/10 accts made the login trows the error every 5 sec.I have debug is relat with  "Status_code is 100"

**Comment by krosenvold** [comment]
this is certainly not only for accounts with the "GOT IT" dialogue. It appears to me that about half my GET_MAP_OBJECTS issues are preceeded with CHECK_CHALLENGE and the other half not. Most accts seem to recover if I use long hold times (i'm typically using 30 minutes or more), but not all of them.

**Comment by jeremydevos** [comment]
@m3g4mlnd how to use old API ?

**Comment by peterchabs** [comment]
Guys this is most definitely an issue with certain coordinates, possibly elevation being off/changed causing unusual activity?  Out of 14 instances I'm running, 2 of them (instance 3 & 9) have these errors repeating themselves over and over again on the same locations. Accounts are all fine/tutorial completed. Last night I rotated the accounts per instance around, this morning same issue on instance 3 & 9, different accounts.

**Comment by peterchabs** [comment]
Probably only tyranitars and dragonites spawning at these locations anyway... no biggie lol

**Comment by krosenvold** [comment]
For what it's worth: I have an instance that ALWAYS fails at 59.915528,10.608857, regardless of which worker is being used. 59.968572,10.785319 is another hot failure spot for me

Additionally, I could add that the GPC scanner manages to scan this exact location, which may indicate that the problem is in the python code and not the hashing service.

12:49:46 | [1] FzYzPmT7c4832: Scanned location 59.968572, 10.785319...
12:49:52 | [1] FzYzPmT7c4832: Found 5 creatures near 59.968572, 10.785319...

**Comment by jeremydevos** [comment]
I still have the same problem with the -novc parameter that forces on the old API

**Comment by jangrewe** [comment]
@jeremydevos `-novc` does not force the old API, it forces the new API (even it if it not deemed safe yet, which may result in b&).

**Comment by jeremydevos** [comment]
Ha thanks, but anyway I have the problem on the 2, according to some it is necessary to use hashing service for it to work now.

**Comment by jangrewe** [comment]
I used to think it's fine to scan without a hash key, but after 48 hours pretty much only solving captchas, i have to concur that you can't really use it without one.

**Comment by Mxchael** [comment]
Same issue is occurring with CHECK_CHALLENGE.

**Comment by M3G4THEKING** [comment]
New server, new ip, new rocketmap install,new accounts all level +3 tut made and TOS ,new hashkey .Still have ERROR "CHECK_CHALLENGE" after login.
Cmd Line: python runserver.py -ac accounts.csv -st 15 -fl -kph 35 -w 40 -hk xxxxxxxxxxxxxxxxxxx -cs -ck xxxxxxxxxxxxxxxxxxxxxxxxxx  -speed
Logs say maybe accounts are banned,but i can login all accounts in app.
![erro](https://cloud.githubusercontent.com/assets/9365134/23994765/bd92a0a8-0a46-11e7-98bb-3a9ba5ef09bb.png)

**Comment by mxab1** [comment]
I have the same problem. All accounts are level 3 and not banned, the IP is also not banned according to the test above and I'm using a valid hashkey. Not one account gets a successful scan.

**Comment by walaoaaa1234** [comment]
```pip uninstall pgoapi```
```pip install -r requirements.txt --upgrade```
try this

**Comment by M3G4THEKING** [comment]
Ok guys,maybe i found the issue in ubuntu 14.04 server, even when we do upgrade  existe some old files who cant or dont let be replaced,first go to your map root and past in putty pip uninstall -r requirements.txt , after you remove all requirements you go to  cd  /usr/local/lib/python2.7/dist-packages/ and check if path pogoapi pgoapi-1.1.6-py2.7.egg-info  protobuf-3.2.0.dist-info  protobuf3_to_dict-0.1.5.egg-info and pycryptodomex-3.4.5.dist-info  check if they are really remove ,if not you can remove by cmd in putty use  rm -r  PATH TO REMOVE  , after your finnish go to your map root and do sudo -H pip install -r requirements.txt , if trows some error about pycryptodomex or another  requirement just past in putty  line for line:   
apt-get purge -y python-pip
wget https://bootstrap.pypa.io/get-pip.py
python ./get-pip.py
apt-get install python-pip

Do again sudo -H pip install -r requirements.txt or  sudo -H pip install -r requirements.txt --upgrade ,this have work for me without any error now.

**Comment by jeremydevos** [comment]
Hello and thank you for your answer, I still cons the same problem after these changes :(, I'm on ubuntu 16, I will test later on a 14

**Comment by jeremydevos** [comment]
On a new server ubuntu 14, i still the same problem :(

**Comment by M3G4THEKING** [comment]
@jeremydevos read my post and check .For me it was the right solution.

**Comment by jeremydevos** [comment]
@m3g4mInD Yes I tested your solution, on ubuntu 16 and ubuntu 14 but it does not work

**Comment by M3G4THEKING** [comment]
@jeremydevos can you post some prints for the steps you do and also the print about your error?

**Comment by jeremydevos** [comment]
@m3g4mInD I did exactly what you said on an ubuntu 16 but I still have the error on it. On a new server (Ubuntu 14), complete installation according to documentation and still the same error.

I have just taken a Debian Wheezy server and I also have the same error.

Error : 

`2017-03-18 17:04:44,907 [   search-worker-0][       captcha][   ERROR] Unable to check captcha: 'CHECK_CHALLENGE'
2017-03-18 17:04:44,909 [   search-worker-0][        search][   ERROR] Map parse failed at 50.639986,3.042009, abandoning location. pokelivefr200 may be banned.. Exception message: KeyError('GET_MAP_OBJECTS',)
Traceback (most recent call last):
  File "/root/RocketMap/pogom/search.py", line 991, in search_worker_thread
    dbq, whq, api, scan_date, account)
  File "/root/RocketMap/pogom/models.py", line 1706, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'GET_MAP_OBJECTS'
`

Server is not banned, account OK with app PokemonGo OK.

**Comment by M3G4THEKING** [comment]
@jeremydevos 
First you go to your root map install
then git pull

After:
go to  cd /usr/local/lib/python2.7/dist-packages/ and delect/remove  this paths:
rm -r pgoapi 
rm -r pgoapi-1.1.6-py2.7.egg-info 
rm -r protobuf-3.2.0.dist-info 
rm -r protobuf3_to_dict-0.1.5.egg-info
rm -r pycryptodomex-3.4.5.dist-info

return to your root map install 

pip install -r requirements.txt or pip install -r requirements.txt --upgrade
Dont forguet to add your hashkey in cmd line  :)

**Comment by jeremydevos** [comment]
@m3g4mInD Hashkey is absolutely required?

**Comment by M3G4THEKING** [comment]
@jeremydevos yes, without haskey you cant scan my friend.

**Comment by dajoker17** [comment]
Just pulled the latest api (update), and it seems this specific (check challenge) issue for me is resolved now.

**Comment by orioncx** [comment]
still actual for me=(. Just have pulled latest version and reinstalled into new virtualenv - same error. 
`'status_code': 100, 'auth_ticket': {'expire_timestamp_ms': 1489929455814L, 'start':'\xa2\xf8,\xc5x\xadE\xab\xf0C8\xc0j<\xcf\xeft\x1f\xa4\xd9\xe7\xe8m\x14o\x0fU\xc4\x0e~\xb8\xc0HUWT\x86\x085Z\x94\x8e\x89\xef\x19(\xdf\xd3T\xedo^\x12\xe2|mIq\xbc\x86\xfd<)', 'end': '\x10\xbf!\x9a\x19\x04\r Wo\xd7\xd8\xff:\x00C'}, 'responses': {}, 'request_id': 4742647504087023624L}
2017-03-19 15:47:35,907 [   search-worker-1][       captcha]
[   ERROR] Unable to check captcha: 'CHECK_CHALLENGE'
`

**Comment by walaoaaa1234** [comment]
```
pip uninstall pgoapi
pip install -r requirements.txt --upgrade
```
``sudo`` if linux, **HASH KEY** is a **NECESSARY** if you want to scan now.

**Comment by SamuHayha** [comment]
Why is this issue closed? I currently have this problem. It is not an account problem, I tried with diferent acc, google & ptc even created new ones to try. I can play ok in the app with the same accounts. I uninstalled everything and started from scratch and still no luck.

**Comment by SamuHayha** [comment]
Ok so, if I got it right, right now a paid hash key is a must in order to scan. If that's so, shouldn't it be a mandatory parameter? If you try to scan without a hashkey it uses the old api which worked for a while but doesn't return any results anymore.
